export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const FIND_PRODUCT = 'FIND_PRODUCT';
export const SWITCH_UPDATE_ON = 'SWITCH_UPDATE_ON';
export const SWITCH_UPDATE_OFF = 'SWITCH_UPDATE_OFF';

export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const SEARCH_INPUT_VALUE = 'SEARCH_INPUT_VALUE';
export const ADD_MANY_PRODUCTS = 'ADD_MANY_PRODUCTS';

export const EDIT_USER = 'EDIT_USER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SWITCH_ACCESS = 'SWITCH_ACCESS';



