export const START_SHOW_NEWS = 'START_SHOW_NEWS';
export const RETURN_INITIAL_DATA = 'RETURN_INITIAL_DATA';
export  const REVERSE_NEWS = 'REVERSE_NEWS'
export  const MORE_INFO = 'MORE_INFO'
export  const CREATE_NEWS = 'CREATE_NEWS'
export const SEARCH_INPUT_VALUE = 'SEARCH_INPUT_VALUE'
export const SWITCH_ADD_NEWS_FLAG = 'SWITCH_ADD_NEWS_FLAG'